version: "3.8"

networks:
  app_network:
    driver: bridge

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app/data:/app/app/data
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app_network
    depends_on:
      prometheus:
        condition: service_healthy
      grafana:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/-/ready"]
      interval: 10s
      retries: 3

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    networks:
      - app_network
    depends_on:
      prometheus:
        condition: service_healthy

volumes:
  grafana_data:
  prometheus_data:
