global:
  scrape_interval: 15s  # How often to scrape targets (default: 1m)

scrape_configs:
  - job_name: 'fastapi_app'
    metrics_path: /docs  
    static_configs:
      - targets: ['app:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
